# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Please describe the task.', null=True, verbose_name='description')),
                ('is_done', models.BooleanField(default=False, verbose_name='done')),
            ],
            options={
                'verbose_name': 'task',
                'default_related_name': 'tasks',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TasksList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tasks list',
                'default_related_name': 'tasks_lists',
                'verbose_name_plural': 'tasks lists',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tasks_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.TasksList', verbose_name='tasks list'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='tasks_list',
        ),
    ]
