# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('title', 'tasks_list')]),
        ),
    ]
